version: '3.8'

services:
  app:
    image: ghcr.io/wirlhawk/nodejs-subscription-tracker
    container_name: nodejs-subscription-tracker
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_URI=mongodb+srv://ray:Rayhan12@cluster0.xt7kx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

    ports:
      - '5500:5500'
    volumes:
      - ./data:/app/data

  